from .text.classification import HFTextClassificationStep
from .text.sentiment import HFSentimentAnalysisStep
from .text.zero_shot import HFZeroShotClassificationStep
from .text.ner import HFNerStep
from .text.fill_mask import HFFillMaskStep
from .text.question_answering import HFQuestionAnsweringStep
from .text.summarization import HFSummarizationStep
from .text.translation import HFTranslationStep
from .text.text_generation import HFTextGenerationStep
from .text.conversational import HFConversationalStep
from .text.text2text import HFText2TextGenerationStep
from .text.multiple_choice import HFMultipleChoiceStep
from .text.table_qa import HFTableQuestionAnsweringStep
from .text.feature_extraction import HFFeatureExtractionStep
from .text.sentence_embeddings import HFSentenceEmbeddingsStep
from .text.sentence_similarity import HFSentenceSimilarityStep
from .text.reranking import HFRerankingStep
from .text.semantic_search import HFSemanticSearchStep
from .text.document_qa import HFDocumentQuestionAnsweringStep
from .text.language_id import HFLanguageIdentificationStep
from .audio.asr import HFAutomaticSpeechRecognitionStep
from .audio.classification import HFAudioClassificationStep
from .audio.tts import HFTextToSpeechStep
from .audio.voice_activity import HFVoiceActivityDetectionStep
from .audio.audio2audio import HFAudioToAudioStep
from .audio.emotion import HFAudioEmotionRecognitionStep
from .audio.speech_conversion import HFSpeechToSpeechStep
from .audio.diarization import HFSpeakerDiarizationStep
from .vision.classification import HFImageClassificationStep
from .vision.detection import HFObjectDetectionStep
from .vision.segmentation import HFImageSegmentationStep
from .vision.captioning import HFImageToTextStep
from .vision.vqa import HFVisualQuestionAnsweringStep
from .vision.zero_shot import HFZeroShotImageClassificationStep
from .vision.depth import HFDepthEstimationStep
from .vision.image2image import HFImageToImageStep
from .vision.inpainting import HFInpaintingStep
from .vision.colorization import HFImageColorizationStep
from .vision.super_resolution import HFImageSuperResolutionStep
from .vision.style_transfer import HFImageStyleTransferStep
from .vision.ocr import HFOcrStep
from .vision.face_detection import HFFaceDetectionStep
from .vision.background_removal import HFImageBackgroundRemovalStep
from .multimodal.doc_vqa import HFDocumentVisualQuestionAnsweringStep
from .multimodal.image_text import HFImageTextToTextStep
from .multimodal.any2any import HFAnyToAnyStep
from .multimodal.table_detection import HFTableDetectionStep
from .vision.video_classification import HFVideoClassificationStep
from .vision.video_interpolation import HFVideoFrameInterpolationStep

