from wpipe import Pipeline
from wpipe_steps.communication import (
    TelegramSendTextStep,
    TelegramSendImageStep,
    TelegramSendFileStep,
)


def print_result(data):
    """Step to print Telegram result."""
    status = data.get("telegram_status", {})
    if status.get("success"):
        print(f"✅ Telegram Action Succeeded: {status}")
    else:
        print(f"❌ Telegram Action Failed: {status.get('error')}")
    return data


def main():
    pipeline_text = Pipeline(pipeline_name="Telegram_Text_Demo", verbose=True)
    pipeline_image = Pipeline(pipeline_name="Telegram_Image_Demo", verbose=True)
    pipeline_file = Pipeline(pipeline_name="Telegram_File_Demo", verbose=True)

    # 1. Text Step: Sends initial completion notification
    pipeline_text.set_steps(
        [
            TelegramSendTextStep(
                name="Send_Telegram_Text",
                bot_token="YOUR_BOT_TOKEN",
            ),
            print_result,
        ]
    )

    # 2. Image Step: Sends chart/photo generated by pipeline
    pipeline_image.set_steps(
        [
            TelegramSendImageStep(
                name="Send_Telegram_Image",
                bot_token="YOUR_BOT_TOKEN",
            ),
            print_result,
        ]
    )

    # 3. File Step: Sends PDF/document report
    pipeline_file.set_steps(
        [
            TelegramSendFileStep(
                name="Send_Telegram_File",
                bot_token="YOUR_BOT_TOKEN",
            ),
            print_result,
        ]
    )

    print("🚀 Starting Complete Telegram Steps Pipeline (Text -> Image -> File)...")

    pipeline_text.run(
        {
            "telegram": {
                # no se envia caption en el mensaje de texto, solo se envia el mensaje, caption sera None, y no se usaria
                "type": "text",
                "message": "Hello from the Telegram pipeline example!",
                "chat_id": "YOUR_CHAT_ID",
            }
        }
    )

    pipeline_image.run(
        {
            "telegram": {
                "type": "image",
                "chat_id": "YOUR_CHAT_ID",
                "caption": "This is a test message sent from the Telegram pipeline example.",
                "message": "/home/william.rodriguez/Documents/w_libraries/w_libraries/wpipe_os/wpipe-steps/wpipe_steps/communication/telegram/examples/media/demo.png",
            }
        }
    )

    pipeline_file.run(
        {
            "telegram": {
                "type": "file",
                "chat_id": "YOUR_CHAT_ID",
                "message": "/home/william.rodriguez/Documents/w_libraries/w_libraries/wpipe_os/wpipe-steps/wpipe_steps/communication/telegram/examples/media/demo.csv",
            }
        }
    )


if __name__ == "__main__":
    main()
