from wpipe import Pipeline
from wpipe_steps.communication import (
    TelegramSendTextStep,
    TelegramSendImageStep,
    TelegramSendFileStep,
)


def print_result(data):
    """Step to print Telegram result."""
    status = data.get("telegram_status", {})
    if status.get("success"):
        print(f"✅ Telegram Action Succeeded: {status}")
    else:
        print(f"❌ Telegram Action Failed: {status.get('error')}")
    return data


def main():
    pipeline = Pipeline(pipeline_name="Telegram_Complete_Demo", verbose=True)

    # 1. Text Step: Sends initial completion notification
    send_text = TelegramSendTextStep.as_step(
        name="Send_Telegram_Text",
        bot_token="YOUR_BOT_TOKEN",
        chat_id="YOUR_CHAT_ID",
        message="🚀 Pipeline execution started! Sending attachments...",
        response_key="telegram_text_status",
    )

    # 2. Image Step: Sends chart/photo generated by pipeline
    send_image = TelegramSendImageStep.as_step(
        name="Send_Telegram_Image",
        bot_token="YOUR_BOT_TOKEN",
        chat_id="YOUR_CHAT_ID",
        image_path="/path/to/chart.png",
        caption="📊 Pipeline analytical chart result",
        response_key="telegram_image_status",
    )

    # 3. File Step: Sends PDF/document report
    send_file = TelegramSendFileStep.as_step(
        name="Send_Telegram_File",
        bot_token="YOUR_BOT_TOKEN",
        chat_id="YOUR_CHAT_ID",
        file_path="/path/to/report.pdf",
        caption="📄 Pipeline full execution report PDF",
        response_key="telegram_file_status",
    )

    # Chain all 3 steps in the pipeline execution flow
    pipeline.set_steps([
        send_text,
        send_image,
        send_file,
        print_result
    ])

    print("🚀 Starting Complete Telegram Steps Pipeline (Text -> Image -> File)...")
    pipeline.run({})


if __name__ == "__main__":
    main()


